/** Presentation registry. Lifecycle dispatch and authorization live in the API. */
const LABELS = { locating_sandbox:'Locating your sandbox', creating_sandbox:'Creating your sandbox',
  starting_sandbox:'Starting or restoring your sandbox', preparing_setup:'Preparing setup',
  checking:'Checking the managed installation', installing:'Installing browser tools',
  configuring:'Configuring the workspace', ready:'Ready', checking_readiness:'Checking workspace readiness',
  registering_preview:'Creating private browser access', waiting_for_toolbox:'Waiting for the sandbox connection; retrying automatically',
  failed:'Setup failed', expired:'Browser link expired', stopped:'Browser access unavailable' };
const ERRORS = {
  insufficient_disk:'Your sandbox needs more free storage. Free up space or contact BayLeaf support.',
  requires_2_gib:'Your sandbox needs more memory. Contact BayLeaf support to upgrade it and keep your files.',
  public_sandbox:'Your sandbox’s privacy settings need attention. Contact BayLeaf support.',
  service_busy:'Another service is being set up. Wait for it to finish, then try again.',
  port_in_use:'The service port is occupied. Setup left that process alone. Contact BayLeaf support.',
  credential_changed:'Sandbox access changed. Set up this service again for a new private link.',
  credential_migration_requires_stop:'This sandbox needs its first credential migration. Save your work and let the machine stop before retrying setup.',
  existing_secret_mounts:'This sandbox has other secret mounts. Contact BayLeaf support to preserve them during migration.',
  sandbox_credential_setup_failed:'Could not attach sandbox access. Retry setup; no ordinary API key was installed.',
  sandbox_access_revoked:'Sandbox access was revoked. Deliberate setup can authorize it again.',
  setup_interrupted:'Setup was interrupted. Retry setup to continue.', setup_timeout:'Setup timed out. Retry setup to continue.',
  installation_failed:'Setup could not finish. Try again, or contact BayLeaf support.',
  application_not_ready:'The workspace did not pass its readiness check. Retry reuses installed applications.',
  personal_key_required:'Create your personal BayLeaf key in the API dashboard first.',
  sandbox_missing:'The shared sandbox is missing. Set up this service to locate or create it.' };
export const SERVICES = [{
  id: 'openchamber',
  name: 'OpenChamber',
  description: 'Build and explore projects with an AI agent connected to BayLeaf.',
  endpoint: '/services/openchamber',
  launch: 'Launch',
   intro: 'First setup creates your sandbox and installs OpenChamber.',
  help: 'OpenChamber is the interface; OpenCode runs the agent. Restart refreshes the BayLeaf configuration and preserves your files and agent history.',
   notes: ['Daytona holds a separate sandbox credential. Programs use its placeholder to access BayLeaf with your shared allowance. Use Chat or the file API to export files and history.'],
  labels: {...LABELS, starting:'Starting OpenChamber', installing_openchamber:'Installing current OpenChamber',
    installing_opencode:'Preparing OpenCode with the upstream installer', starting_openchamber:'Starting OpenChamber',
    waiting_for_opencode:'Waiting for OpenCode to respond', connecting_bayleaf:'Connecting your BayLeaf account', loading_tools:'Loading BayLeaf tools and skills'},
  errors: {...ERRORS, node_22_required:'Your sandbox’s software needs an update. Contact BayLeaf support.',
    provider_configuration_unavailable:'Could not connect your sandbox to BayLeaf. Try again.',
    opencode_installation_failed:'OpenChamber could not install OpenCode. Retry setup to try the download again.'},
}, {
  id: 'nanobot', name: 'Nanobot', endpoint: '/services/nanobot', launch: 'Launch',
  description: 'Work with an AI agent in a simpler chat interface, with BayLeaf tools and shared sandbox files.',
   intro: 'First launch installs Nanobot 0.3.5.',
  help: 'Projects use /home/daytona/workspace on the server. Nanobot keeps its own conversations and memory. Restart or link renewal may reconnect Nanobot without affecting other apps.',
   notes: ['Uses your shared BayLeaf allowance through a sandbox-specific credential held by Daytona; only its placeholder is stored in the sandbox.',
    'Dream, heartbeat and idle compaction start off; no schedules are created. Saved conversations and memory are not covered by inference zero-data-retention.',
    'BayLeaf search, fetch, usage and private previews are available. These tools do not reproduce OpenCode approval prompts.'],
  labels: {...LABELS, starting:'Starting Nanobot', installing_nanobot:'Installing Nanobot 0.3.5',
    starting_nanobot:'Starting Nanobot', configuring_preview:'Connecting the private browser address'},
  errors: {...ERRORS, python_311_required:'Nanobot needs Python 3.11 or newer. Contact BayLeaf support.',
    node_22_required:'BayLeaf tools need Node 22 or newer. Contact BayLeaf support.',
    managed_file_changed:'A managed tool or skill was edited. Setup preserved it. Contact BayLeaf support to reconcile the change.',
    provider_configuration_unavailable:'The current BayLeaf model configuration is unavailable. Try again later.',
    preview_configuration_invalid:'Nanobot could not confirm its private browser address. Try setup again.'},
}, {
  id: 'code-server', name: 'code-server (VS Code)', endpoint: '/services/code-server', launch: 'Launch',
  description: 'Edit code, use a terminal, and add extensions with VS Code in your browser.',
  intro: 'First launch installs code-server and creates your sandbox if needed.',
  help: 'Restart checks the managed installation and relaunches the editor. Your workspace files, editor settings, and extensions stay in the sandbox.',
  notes: ['Extensions share sandbox memory with your other apps.'],
  labels: {...LABELS, starting:'Starting code-server', installing_code_server:'Installing verified code-server release', starting_code_server:'Starting code-server'},
  errors: {...ERRORS, release_verification_failed:'The release download could not be verified. Try again later.',
    unsupported_architecture:'This managed release needs a Linux amd64 sandbox. Contact BayLeaf support.'},
}, {
  id: 'jupyter', name: 'JupyterLab', endpoint: '/services/jupyter', launch: 'Launch',
  description: 'Explore data and run Python notebooks in your shared workspace.',
   intro: 'First launch installs JupyterLab.',
  help: 'Notebooks, terminals, and the file browser use your existing workspace. Restart preserves files and settings.',
  notes: ['Kernels share sandbox memory with your other apps. No BayLeaf inference key is installed.'],
  labels: {...LABELS, starting:'Starting JupyterLab', installing_jupyter:'Installing JupyterLab', starting_jupyter:'Starting JupyterLab'},
  errors: {...ERRORS, python_311_required:'JupyterLab needs Python 3.11 or newer. Contact BayLeaf support.',
    managed_file_changed:'Your Jupyter configuration was edited. Setup preserved it. Contact BayLeaf support to reconcile the change.'},
}, {
  id: 'ttyd', name: 'Shell (ttyd)', endpoint: '/services/ttyd', launch: 'Launch',
  description: 'Run shell commands in your shared workspace from the browser.',
  intro: 'First launch installs ttyd, a small browser terminal.',
  help: 'Each connection opens a new shell in /home/daytona/workspace. Disconnecting closes that shell; reconnecting starts a new one. Restart affects this app’s terminals.',
  notes: ['Files persist, terminal sessions do not. Commands run as your normal sandbox user and can access the same files and credentials as other apps. No BayLeaf inference key is installed.'],
  labels: {...LABELS, starting:'Starting Shell (ttyd)', installing_ttyd:'Installing verified ttyd release', starting_ttyd:'Starting Shell (ttyd)'},
  errors: {...ERRORS, release_verification_failed:'The release download could not be verified. Try again later.',
    unsupported_architecture:'This managed release needs a Linux amd64 sandbox. Contact BayLeaf support.'},
}, {
  id: 'dufs', name: 'Files (dufs)', endpoint: '/services/dufs', launch: 'Launch',
  description: 'Browse, upload, download, and edit your workspace files in your browser.',
  intro: 'First launch installs the file server and creates your sandbox if needed.',
  help: 'Restart checks the managed installation and relaunches the file server. Workspace files stay in place.',
  notes: ['Serves your workspace folder, not your entire home directory. Upload, text editing, deletion, search, archive download, and file hashes are enabled. Changes affect the same files used by your other sandbox tools. Links to files outside this folder are not served.'],
  labels: {...LABELS, starting:'Starting the file server', installing_dufs:'Installing verified dufs release', starting_dufs:'Starting the file server'},
  errors: {...ERRORS, release_verification_failed:'The release download could not be verified. Try again later.',
    unsupported_architecture:'This managed release needs a Linux amd64 sandbox. Contact BayLeaf support.'},
}] as const;
