/**
 * Documentation Routes
 *
 * Machine-facing API documentation served under /docs:
 *   GET /docs               — Interactive API docs (Scalar viewer)
 *   GET /docs/SKILL.md      — Agent skill file describing BayLeaf's machine-facing API surface
 *
 * The OpenAPI spec itself is auto-generated by @hono/zod-openapi and served
 * from index.ts via app.doc31(). This file only provides the Scalar HTML
 * wrapper and the SKILL.md builder.
 *
 * These endpoints are all public and unauthenticated.
 */

import { OpenAPIHono } from '@hono/zod-openapi';
import type { AppEnv } from '../types';
import { getModelName } from '../openrouter';

export const docsRoutes = new OpenAPIHono<AppEnv>();

// ── GET / — Scalar API reference viewer ───────────────────────────

docsRoutes.get('/', (c) => {
  const html = `<!doctype html>
<html>
<head>
  <title>BayLeaf API Reference</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>
  <script id="api-reference" data-url="/docs/openapi.json"></script>
  <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
</body>
</html>`;
  return c.html(html);
});

// ── GET /SKILL.md ─────────────────────────────────────────────────

docsRoutes.get('/SKILL.md', async (c) => {
  const model = c.env.RECOMMENDED_MODEL;
  const name = await getModelName(model) ?? model;
  const content = buildSkillMd(model, name);
  return c.text(content, 200, { 'Content-Type': 'text/markdown; charset=utf-8' });
});

// ── SKILL.md builder ──────────────────────────────────────────────

function buildSkillMd(model: string, modelName: string): string {
  const bt = '`';
  const fence = '```';

  return `---
name: bayleaf-api
description: Use the BayLeaf API for LLM inference, sandboxed code execution, and model discovery at UC Santa Cruz.
---

# BayLeaf API

BayLeaf API (${bt}https://api.bayleaf.dev${bt}) provides free LLM inference and sandboxed
code execution for the UC Santa Cruz campus community. All inference uses
zero-data-retention providers — conversations are never used for training.

Full OpenAPI 3.1 spec: ${bt}https://api.bayleaf.dev/docs/openapi.json${bt}

---

## Authentication

All machine-facing endpoints accept ${bt}Authorization: Bearer <key>${bt}.

| Method | When to use |
|--------|-------------|
| **BayLeaf key** (${bt}sk-bayleaf-...${bt}) | Off-campus, or when you need a persistent sandbox and file access. Provision free at ${bt}https://api.bayleaf.dev/${bt}. |
| **Campus Pass** (omit header) | On the UCSC campus network. No key needed. Sandbox access is ephemeral (one-shot). |

Daily spending limit per key: $1 (resets daily). All rate limiting is handled by the
upstream provider — the API itself imposes no request-rate limits.

---

## LLM Inference

BayLeaf is an OpenAI-compatible proxy. Point any OpenAI-compatible client at
${bt}https://api.bayleaf.dev/v1${bt} with your key and it works.

### Chat Completions

${fence}
POST /v1/chat/completions
Content-Type: application/json
Authorization: Bearer sk-bayleaf-...

{
  "model": "${model}",
  "messages": [
    { "role": "user", "content": "Explain the halting problem in one paragraph." }
  ]
}
${fence}

Supports ${bt}stream: true${bt} for SSE streaming. All standard OpenAI parameters
(${bt}temperature${bt}, ${bt}max_tokens${bt}, ${bt}tools${bt}, etc.) are forwarded to OpenRouter.

### Responses API

${fence}
POST /v1/responses
Content-Type: application/json
Authorization: Bearer sk-bayleaf-...

{
  "model": "${model}",
  "input": "What is the capital of France?"
}
${fence}

### Other OpenRouter endpoints

Any ${bt}/v1/*${bt} path is proxied directly to OpenRouter. This includes endpoints like
${bt}/v1/models${bt} (list available models), ${bt}/v1/auth/key${bt} (check your key usage),
and any future OpenRouter endpoints. The proxy does no model filtering — any model
ID accepted by OpenRouter works.

---

## Sandboxed Code Execution

BayLeaf provides sandboxed Linux environments for running code.

### Execute a command

${fence}
POST /sandbox/exec
Content-Type: application/json
Authorization: Bearer sk-bayleaf-...

{
  "command": "python3 -c \\"print(2+2)\\"",
  "workdir": "/home/daytona/workspace"
}
${fence}

Response:

${fence}json
{ "exitCode": 0, "output": "4\\n" }
${fence}

- Commands run under ${bt}set -e -o pipefail${bt} with a 120-second timeout.
- The sandbox is a full Debian-based Linux environment with network access.
- ${bt}workdir${bt} defaults to ${bt}/home/daytona/workspace${bt} if omitted.
- **Keyed users** get a persistent sandbox that survives across requests.
- **Campus Pass users** get an ephemeral sandbox that is created and destroyed per-request.

### Download a file

${fence}
GET /sandbox/files/home/daytona/workspace/output.txt
Authorization: Bearer sk-bayleaf-...
${fence}

Returns the raw file bytes. Requires a BayLeaf API key (persistent sandbox only).

### Upload a file

${fence}
PUT /sandbox/files/home/daytona/workspace/input.txt
Authorization: Bearer sk-bayleaf-...
Content-Type: application/octet-stream

<file bytes>
${fence}

Response:

${fence}json
{ "success": true, "path": "/home/daytona/workspace/input.txt", "bytes": 1234 }
${fence}

Parent directories are created automatically. Requires a BayLeaf API key.

### Destroy sandbox

${fence}
DELETE /sandbox
Authorization: Bearer sk-bayleaf-...
${fence}

Permanently destroys the sandbox and all its data.

---

## Model Recommendation

The recommended model changes over time. Fetch the current recommendation:

${fence}
GET /recommended-model
${fence}

Response:

${fence}json
{ "model": "${model}", "name": "${modelName}" }
${fence}

No authentication required.

---

## OpenCode Setup

To use BayLeaf as an [OpenCode](https://opencode.ai) provider:

### 1. Add provider config

Add to ${bt}~/.config/opencode/opencode.json${bt} (create if needed; merge into existing
${bt}"provider"${bt} object if the file already exists):

${fence}json
{
  "$schema": "https://opencode.ai/config.json",
  "provider": {
    "bayleaf": {
      "npm": "@ai-sdk/openai-compatible",
      "name": "BayLeaf API",
      "options": {
        "baseURL": "https://api.bayleaf.dev/v1"
      },
      "models": {
        "${model}": {
          "name": "${modelName}"
        }
      }
    }
  }
}
${fence}

Restart OpenCode after any config change.

### 2. Store the API key

Run ${bt}/connect${bt} in OpenCode, select **BayLeaf API** (under **Other**), and paste
your ${bt}sk-bayleaf-...${bt} key.

### 3. Select the model

Run ${bt}/models${bt} and select ${bt}${model}${bt} under BayLeaf API.

---

## pi Setup

To use BayLeaf with the [pi coding agent](https://github.com/badlogic/pi-mono)
(${bt}npm install -g @mariozechner/pi-coding-agent${bt}):

### 1. Store the API key

${fence}bash
mkdir -p ~/.tokens && chmod 700 ~/.tokens
echo -n 'sk-bayleaf-...' > ~/.tokens/bayleaf-api
chmod 600 ~/.tokens/bayleaf-api
${fence}

### 2. Add provider config

Create or edit ${bt}~/.pi/agent/models.json${bt}:

${fence}json
{
  "providers": {
    "bayleaf": {
      "baseUrl": "https://api.bayleaf.dev/v1",
      "apiKey": "!cat ~/.tokens/bayleaf-api",
      "api": "openai-completions",
      "models": [
        {
          "id": "${model}",
          "name": "${modelName} (BayLeaf)"
        }
      ]
    }
  }
}
${fence}

The ${bt}!${bt} prefix tells pi to resolve the value by running a shell command.
If you prefer, you can set ${bt}BAYLEAF_API_KEY${bt} in your environment and use
${bt}"apiKey": "BAYLEAF_API_KEY"${bt} instead (pi checks env vars by name before
treating the string as a literal).

### 3. Use the model

${fence}bash
pi --model bayleaf/${model} "Help me refactor this code"
${fence}

Or launch interactively and switch with ${bt}Ctrl+P${bt}:

${fence}bash
pi --model bayleaf/${model}
${fence}

---

## Goose Setup

To use BayLeaf with [Goose](https://github.com/block/goose)
(${bt}curl -fsSL https://github.com/block/goose/releases/latest/download/install.sh | sh${bt}).
Requires Goose **1.29+**.

### 1. Create a custom provider file

Create ${bt}~/.config/goose/custom_providers/bayleaf.json${bt}:

${fence}json
{
  "name": "bayleaf",
  "engine": "openai",
  "display_name": "BayLeaf API",
  "description": "OpenRouter-proxying LLM inference for UC Santa Cruz. Zero-data-retention.",
  "api_key_env": "BAYLEAF_API_KEY",
  "base_url": "https://api.bayleaf.dev/v1/chat/completions",
  "models": [
    {
      "name": "${model}",
      "context_limit": 128000,
      "max_tokens": 16384
    }
  ],
  "supports_streaming": true
}
${fence}

### 2. Store the API key

Run ${bt}goose configure${bt}, select **BayLeaf API** from the provider list, and paste
your ${bt}sk-bayleaf-...${bt} key. Goose stores it in your system keychain.

Alternatively, set ${bt}BAYLEAF_API_KEY${bt} in your environment for the session.

### 3. Use the model

${fence}bash
GOOSE_PROVIDER=bayleaf GOOSE_MODEL=${model} goose session
${fence}

Or for non-interactive use:

${fence}bash
GOOSE_PROVIDER=bayleaf GOOSE_MODEL=${model} goose run --text "Help me refactor this code"
${fence}
`;
}
