/**
 * Documentation Routes
 *
 * Machine-facing documentation served under /docs:
 *   GET /docs                        — Interactive API docs (Scalar viewer, public)
 *   GET /docs/SKILL.md               — 301 -> /llms.txt (legacy)
 *   GET /docs/gws-oauth-client.json — Google Workspace CLI OAuth client config (authenticated or campus)
 *
 * The OpenAPI spec itself is auto-generated by @hono/zod-openapi and served from
 * index.ts via app.doc31(). Onboarding/extension content for agents (formerly the
 * SKILL.md body) now lives at /llms.txt; see routes/llms.ts for rationale.
 */

import { OpenAPIHono } from '@hono/zod-openapi';
import type { AppEnv, UserKeyRow } from '../types';
import { getSession } from '../utils/session';
import { isCampusPassEligible } from '../utils/ip';
import { BAYLEAF_TOKEN_PREFIX } from '../constants';

export const docsRoutes = new OpenAPIHono<AppEnv>();

// ── GET / — Scalar API reference viewer ───────────────────────────

docsRoutes.get('/', (c) => {
  // lang="en" is required for WCAG 3.1.1 (Language of Page). The Scalar viewer
  // renders its own chrome inside this shell but does not set it for us, so the
  // attribute has to live here.
  const html = `<!doctype html>
<html lang="en">
<head>
  <title>BayLeaf API Reference</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>
  <script id="api-reference" data-url="/docs/openapi.json"></script>
  <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
</body>
</html>`;
  return c.html(html);
});

// ── GET /SKILL.md — legacy redirect to /llms.txt ──────────────────
//
// SKILL.md was the wrong abstraction for BayLeaf: agents don't need to load
// BayLeaf-specific instructions per-conversation, they only need to be configured
// against the OpenAI-compatible /v1/* endpoints once. Onboarding and capability-
// extension content now lives at /llms.txt (site-level discovery, one-time read).

docsRoutes.get('/SKILL.md', (c) => c.redirect('/llms.txt', 301));

// ── Auth helper for docs routes ───────────────────────────────────

/**
 * Resolve the user's email from session, Bearer token, or Campus Pass.
 * Returns the email if identified, or 'campus' for anonymous campus users.
 * Returns null if no valid auth is present.
 */
async function resolveDocsUser(c: import('hono').Context<AppEnv>): Promise<string | null> {
  // Try session cookie first (browser users)
  const session = await getSession(c);
  if (session) return session.email;

  // Try Bearer token (agents)
  const authHeader = c.req.header('Authorization');
  const token = authHeader?.replace(/^Bearer\s+/i, '').trim();
  if (token && token.startsWith(BAYLEAF_TOKEN_PREFIX)) {
    const row = await c.env.DB.prepare(
      'SELECT email FROM user_keys WHERE bayleaf_token = ? AND revoked = 0',
    ).bind(token).first<UserKeyRow>();
    if (row) return row.email;
  }

  // Campus Pass (on-campus IP, no credentials needed)
  if (isCampusPassEligible(c.req.raw, c.env)) {
    return 'campus';
  }

  return null;
}

/** Check whether GWS distribution is configured (all three env vars present). */
function gwsConfigured(env: AppEnv['Bindings']): boolean {
  return !!(env.GWS_CLIENT_ID && env.GWS_CLIENT_SECRET && env.GWS_PROJECT_ID);
}

/**
 * Build the OAuth client config from env vars (Google Desktop/"installed app" format).
 *
 * Google treats installed-app client secrets as non-confidential: the security of
 * the gws flow comes from the per-user browser OAuth consent (+ PKCE), not from this
 * file. Every user receives the same shared config. The auth gate on the route below
 * is therefore an abuse/quota control tied to campus identity, NOT a confidentiality
 * control: widening it would not leak a secret, only widen who consumes our GCP quota.
 * The served file is still named client_secret.json on disk because the gws CLI
 * requires that exact path (~/.config/gws/client_secret.json).
 */
function buildOauthClientJson(env: AppEnv['Bindings']): object {
  return {
    installed: {
      client_id: env.GWS_CLIENT_ID,
      project_id: env.GWS_PROJECT_ID,
      auth_uri: 'https://accounts.google.com/o/oauth2/auth',
      token_uri: 'https://oauth2.googleapis.com/token',
      auth_provider_x509_cert_url: 'https://www.googleapis.com/oauth2/v1/certs',
      client_secret: env.GWS_CLIENT_SECRET,
      redirect_uris: ['http://localhost'],
    },
  };
}

docsRoutes.get('/gws-oauth-client.json', async (c) => {
  if (!gwsConfigured(c.env)) {
    return c.json({ error: 'Google Workspace CLI distribution is not configured on this deployment.' }, 404);
  }

  const user = await resolveDocsUser(c);
  if (!user) {
    return c.json({ error: 'Authentication required. Sign in at https://api.bayleaf.dev/, use Authorization: Bearer sk-bayleaf-..., or access from the campus network.' }, 401);
  }

  const oauthClient = buildOauthClientJson(c.env);
  return c.json(oauthClient, 200);
});
